# Generated by Django 4.2.5 on 2023-09-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kylym', '0002_statistic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'verbose_name': 'Ментор'},
        ),
        migrations.AddField(
            model_name='mentor',
            name='image',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
