# Generated by Django 4.2.5 on 2023-10-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kylym', '0003_alter_mentor_options_mentor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
