# Generated by Django 4.2.5 on 2023-10-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kylym', '0004_sponsor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={},
        ),
        migrations.AddField(
            model_name='sponsor',
            name='second_image',
            field=models.ImageField(default='important one', upload_to=''),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
    ]
