# Generated by Django 4.2.5 on 2023-10-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kylym', '0006_body_mentor_describtion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
